### ISSUE TITLE
server.OnDispose and server.OnInit

### ISSUE THREAD

**Issue by damianh** [owin/owin#27]
I'm building middleware components that have lifecycle and disposal concerns. I need a way to clean up. In the katana world this key is `host.OnAppDisposing`. Using `server` here because of #24 .

Required | Key Name | Value Description
--- | --- | ---
No | server.OnInit | An `Action<Func<Task>>` that allows middleware to register a callback that the server will call once when initializing.
No | server.OnDispose | A `CancellationToken` that represents when the server is disposing.

Note: some vendor implementations have used `host.OnAppDisposing` as a key fullfilling the same function as server.OnDispose. Builder authors MAY use the vendor key and use the CancellationToken value to provide server.OnDispose. Middleware authors MUST use server.OnDispose if it is present. In order to ensure the migration to the standard keys, middleware SHOULD notify users of the lack of server.OnDispose key, and suggest an appropriate builder / server, or degrade gracefully.

**Comment by panesofglass** [comment]
Ping! Is this ready for a vote?

**Comment by serialseb** [comment]
I suggest the simplest thing that could possibly work and would make much sense, two keys, optional, one for starting, one for disposing? We could get a consensus amongst implementers rather quick if we do it over skype or talk about it on gitter, I'm available this week, we can probably fast forward this. 
Any init order I have abandoned, I've moved on to other simpler methods, so I'd be happy with .OnInit / OnDisposing.

**Comment by damianh** [comment]
@serialseb I'm with you on that (no init order); but do both keys need to be part of this proposal?

Question for everyone, key name in this proposal:

 1. `server.OnDispose`
 2. `server.OnDisposing`
 3. `server.OnAppDisposing`

Personally I prefer 1.

**Comment by panesofglass** [comment]
@damianh there's prior art [here](https://msdn.microsoft.com/en-us/library/microsoft.owin.builderproperties.appproperties.onappdisposing%28v=vs.113%29.aspx). I'm partial to moving to the `server` prefix using 2 above but wonder whether others may be interested in retaining `host.OnAppDisposing`.

**Comment by panesofglass** [comment]
@serialseb, should we split the two or add `server.OnInit` to this proposal? I think I would prefer to create a second and vote on them separately, but I'm open to either.

**Comment by serialseb** [comment]
It seems silly to do two proposals for two keys for lifetime management no? It's a one liner to add to your list and we're good.
For host, I say it's a vendor prefix here and I'd prefer the standard didn't standardise those. I'd go for server.OnDispose and server.OnInit, with a note that a vendor implemented a custom key on host and middlewares may want to use the old version when detecting, should they wish to. That'll encourage people to move away from those non-standard keys, and it can be provided by any system that wants to be compatible with those old keys. Happy to put it to the vote and go with the majority, but i'd rather go for server.OnDispose / server.OnInit, one proposal, to be put to vote immediately.

**Comment by damianh** [comment]
+1 @serialseb  `server.OnDispose` and `server.OnInit` with vendor note.

**Comment by khellang** [comment]
:+1: on `server.OnDispose` and `server.OnInit`

**Comment by damianh** [comment]
I'll update the issue at the top.

Where would these keys be defined? Under 3.2.3 Other Data?

**Comment by damianh** [comment]
- Changed the title of the issue to include OnInit.
 - Updated the issue: renamed `server.OnAppDisposing` to `server.OnDispose` and added the `server.OnInit` key.

**Comment by damianh** [comment]
@panesofglass This is ready for the vote :)

**Comment by damianh** [comment]
We'll need a note re: katana's server.OnAppDisposing key

**Comment by panesofglass** [comment]
:+1: for me

**Comment by panesofglass** [comment]
:+1:

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by EddieGarmon** [comment]
:+1:

**Comment by damianh** [comment]
+1

**Comment by khellang** [comment]
:+1:

**Comment by serialseb** [comment]
:+1:

**Comment by darrelmiller** [comment]
+1

**Comment by skoon** [comment]
+1

I'm not cool enough for emoji :(

**Comment by panesofglass** [comment]
I think we can close this and add it with unanimous support.

**Comment by panesofglass** [comment]
I'll leave the issue open until we update the spec with the additional keys. @serialseb, how is the revised spec coming? Should we add it there or add it to the current format?

**Comment by serialseb** [comment]
You can always add it to the 1.1 draft that exists, and i'll fold it in my pull request for 1.0.1 when it's ready?

**Comment by panesofglass** [comment]
@serialseb, sounds good.

**Comment by panesofglass** [comment]
I added a PR for this. @skoon, is moving `CommonKeys.md` to the root something you can account for when generating the site at https://github.com/owin/owin.github.io?

**Comment by skoon** [comment]
yup
