### ISSUE TITLE
Web owin.org charset

### ISSUE THREAD

**Issue by bigpcz** [owin/owin#34]
Hi, 

I can see wrong characters in the OWIN spec. extensions:
http://owin.org/spec/extensions/owin-SendFile-Extension-v0.2.0.htm

![qmchar](https://cloud.githubusercontent.com/assets/7683458/6203401/980b6fa4-b520-11e4-9aca-a1414620ed76.png)

It doesn't look professional and should be fixed.

**Comment by serialseb** [comment]
Feel free to submit a pull request. I don't know if anyone has their names on that spec.

**Comment by panesofglass** [comment]
In particular, we'd love to finish rewriting all these things as markdown. The tokens you see are a result of generating markup from Word.

**Comment by panesofglass** [comment]
Duplicate of #18
