### ISSUE TITLE
Web owin.org: links

### ISSUE THREAD

**Issue by bigpcz** [owin/owin#35]
Clicking the menu item opens the page as a new tab instead of jumping to the section on the same page only. It is quite irritating.

**Comment by skoon** [comment]
? huh, I didn't notice a base target set anywhere. I'll look again.

**Comment by xt0rted** [comment]
@skoon the target is set in the `head` tag.

``` html
<html>
<head>
    <title>OWIN &mdash; Open Web Interface for .NET</title>
    <link href='http://fonts.googleapis.com/css?family=Nunito:700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="style.css"/>
    <base target="_blank"/>
</head>
<body>
```

**Comment by panesofglass** [comment]
@xt0rted, thanks for pointing that out! @skoon, was that intentional? I guess it helps for external links.

**Comment by skoon** [comment]
![Dunno](http://media.giphy.com/media/135X3vYgOotq5a/giphy.gif)

**Comment by skoon** [comment]
OK, removed the base target for the page. People can middle-click or "open in new tab/window" if they want.

**Comment by panesofglass** [comment]
Thanks, @skoon!
