### ISSUE TITLE
Web owin.org: title

### ISSUE THREAD

**Issue by bigpcz** [owin/owin#36]
The title says: OWIN: Open Web Interface for .NET
Shouldn't the title be "Open Web Server Interface for .NET"? I thought for the first time that OWIN is something like REST/Json, the interface between the client application and the web server and it is interface between the web server and its modules. Correct me please if I am wrong here.

**Comment by serialseb** [comment]
An interface is a contract that two parties intend to support to communicate. If a component interface is an interface for a component, then a web interface is an interface for the web. In the context of components on .net, it is an interface for components doing web things. I don't believe the semantics are necessarily incorrect, nor does the interface itself differ much between a server and its components and a client and a server, conceptually, for those interfaces model a request, a response and the associated data that is expected to be present for such request/response.

From where I stand I don't see a problem. Then again, having coined the term, I'm probably biased.

**Comment by panesofglass** [comment]
Closing for lack of continued discussion and therefore assuming lack of interest.
