### ISSUE TITLE
Revise governance model

### ISSUE THREAD

**Issue by panesofglass** [owin/owin#38]
I propose we replace the current governance model with a much simpler, majority rules model.

1. Monthly, community call with recorded minutes.
2. Active community participants, defined as those building implementations, chatting in public forums, or presenting, are welcome to attend pending no existing community member objects.
3. Post public agenda 2 weeks before meeting.
4. No proposal becomes a standard until at least two, independent implementations have been submitted.

**NOTE: This proposal will be automatically accepted 2 weeks following the last change to this description field unless someone objects.**

[edit to keep the discussion open]

**Comment by damianh** [comment]
+1

**Comment by serialseb** [comment]
I think we ought to put some timelines on voting. Aka 2 weeks before once the editors are happy with the specification. Active members vs Inactive members should also have a time since last contributed (or self-revoked), but limited to admin rights on the site to tag, assign labels etc.

**Comment by panesofglass** [comment]
Accepted with amendment to cut off voting after two weeks. In general, the guideline should be to favor momentum rather than formality.
