### ISSUE TITLE
Builder Specification

### ISSUE THREAD

**Issue by khellang** [owin/owin#39]
Since `MidFunc` has been voted on and accepted (see #6), the next logical step is to get an "official" discussion going on a `BuildFunc` (or `BuildAction`?).

As I understand it, the current proposal is (as used by @serialseb)

```csharp
Action<Func<IDictionary<string, object>, MidFunc>>
```

Where `IDictionary<string, object>` is the startup properties.
I would also like to split this signature into a separate `MidFactoryFunc`

```csharp
Func<IDictionary<string, object>, MidFunc>
```

Then the `BuildFunc` would be defined as

```csharp
Action<MidFactoryFunc>
```

This would result in the following set of funcs

```csharp
delegate Task AppFunc(IDictionary<string, object> env);
delegate AppFunc MidFunc(AppFunc next);
delegate MidFunc MidFactoryFunc(IDictionary<string, object> props);
delegate void BuildFunc(MidFactoryFunc factory);
```

An OWIN pipeline could then be composed as follows:

```csharp
var factories = new List<MidFactoryFunc>();
BuildFunc builder = factories.Add;

// Invoke builder to add middleware.

var props = new Dictionary<string, object>(StringComparer.Ordinal);
IEnumerable<MidFunc> middleware = factories.Select(factory => factory(props));

AppFunc endMiddleware = _ => Task.CompletedTask;
AppFunc app = middleware.Reverse().Aggregate(endMiddleware, (appFunc, next) => next(appFunc));

// Invoke app on request.
```

Middleware authors would then hang their `Use*` methods off `BuildFunc`, like this

```csharp
public static BuildFunc UseMyAwesomeMiddleware(this BuildFunc builder)
{
    builder(props => next => env => Task.CompletedTask);
    return builder;
}
```

What do you think? Does anyone care about this?

I remember @nikmd23 having some concerns around `MidFunc` and diagnostics etc.. Is this something that should/must be considered here?

**Comment by khellang** [comment]
I think a `BuildFunc` specification is getting more important now that there are more and more builder implementations out there. It would be nice not having to ship `Middleware.Katana`, `Middleware.AspNet`, `Middleware.Nowin` etc. packages just to simply add discoverability for your middleware on different implementations.

FYI, ASP.NET 5 provides an OWIN "bridge" in [OwinExtensions.cs](https://github.com/aspnet/HttpAbstractions/blob/516a435ea5f64105d5a5e04c727f5cd1b542f48b/src/Microsoft.AspNet.Owin/OwinExtensions.cs). They're using an `Action<MidFunc>` delegate, lacking startup properties, right now. It would be nice to have a specification ready before this hits RTM.

**Comment by damianh** [comment]
I think we should still ship Katana (IAppBuilder) and AspNet (IApplicationBuilder) integration packages. They should be out-of-band with core bits though. Dunno what Middleware.Nowin is...

**Comment by nikmd23** [comment]
@khellang I do have concerns, mostly about a way to identify a `MidFunc`. It's had to tell a user that a piece of middleware has executed, when there isn't currently a way to name it. 

Sure, there are times when a name can be derived (the `app.Use<FooMiddleware>()` pattern would be called *Foo* for example), but it'd be much better if there was a standard environment key or something that could be used.

**Comment by khellang** [comment]
@nikmd23 So what you want is an equivalent to `Function.name` in ES6? :smile:

**Comment by nikmd23** [comment]
That'd be awesome!

On Wed, Aug 26, 2015 at 10:17 AM, Kristian Hellang <notifications@github.com

**Comment by khellang** [comment]
One solution could be to use the startup properties as a two-way communication between the builder and the middleware.

Then you could do something like

```csharp
public static BuildFunc UseMyAwesomeMiddleware(this BuildFunc builder)
{
    builder(props =>
    {
        props["owin.MiddlewareName"] = "MyAwesomeMiddleware";
        return next => env => Task.CompletedTask;
    });
    return builder;
}
```

The builder could then check for the presence of `owin.MiddlewareName` and use that, or fall back to `ToString` or `.GetType().Name` of the `MidFunc` delegate (remember, you can return a named delegate).

**Comment by nikmd23** [comment]
I'm not really too particular about how it works, just that its setup to
work. Of course the secondary hurdle is adoption by middleware
implementors.

On Wed, Aug 26, 2015 at 10:39 AM, Kristian Hellang <notifications@github.com

**Comment by panesofglass** [comment]
@serialseb, you mentioned you did something to expose the middleware pipeline. Were you leveraging classes to identify the names of the middleware?

**Comment by serialseb** [comment]
Pull request on middleware and buildfunc coming in a short while today.

@panesofglass yes, class names if I can get them (using magic), or write-only keys (middleware.Name), or empty if it's something I can't extract.

**Comment by serialseb** [comment]
Pull request at #41, suggest closing this and moving to the pull request for conversation?

**Comment by panesofglass** [comment]
Please direct conversation to #41.
