### ISSUE TITLE
How can I unit test OAuth2 authentication on Web API using Microsoft.Owin.Testing?

### ISSUE THREAD

**Issue by SetTrend** [owin/owin#48]
Hi,

given the following VS solution setup:

```
MySolution
| -- WebApiProject
| -- UnitTestProject
```

I have installed the `Microsoft.Owin.Diagnostics` and `Microsoft.Owin.Testing` NuGet packages.

Now I want to test internal and external authentication using this set-up. How can I do this?

I have been googling this but can't find any documentation on how to apply TestServer here.

Thank you for enlightening me.

**Comment by serialseb** [comment]
Sorry, unfortunately you're in the wrong group. We're the OWIN working group and we work on the OWIN specifications (at owin.org).
You're looking for support on Katana, which is a Microsoft product, so you may want to be looking at discussing this on jabbr where there are rooms with Microsoft people, or the repositories for asp.net at github.com/aspnet.
