### ISSUE TITLE
Website/DNS down

### ISSUE THREAD

**Issue by unencode** [owin/owin#51]
Hi. Not sure where else to contact you but owin.org is down. Looks like a DNS hijack-ish type thing.

**Comment by serialseb** [comment]
No, just waiting for the change in dns providers to propagate...

**Comment by serialseb** [comment]
Will report when new info becomes available or i find what wrong manipulation i made

**Comment by unencode** [comment]
Great, thanks. Just saw some weird-looking stuff at:
https://who.is/whois/owin.org

**Comment by serialseb** [comment]
Nah that's just my details. Lol.

**Comment by serialseb** [comment]
Should have propagated, let me know if you still encounter any issue.

**Comment by unencode** [comment]
Yes, it works now, thanks!

-Isaac

**Comment by serialseb** [comment]
Fabulous. Closing this. And I won't take it personally about the `weird` thing. :-D

**Comment by unencode** [comment]
Sorry! lol man. Thanks for taking care of OWIN, it's awesome!

**Comment by serialseb** [comment]
Haha no problem and thank you :) Im but the name owner :)
