### ISSUE TITLE
how can I add middleware to OWIN Pipeline after Startup at runtime

### ISSUE THREAD

**Issue by HarveerNehra** [owin/owin#52]
I have added all available middleware in OWIN Pipeline in Startup class using IAppBuilder to authenticate user in my project. It is working fine. But how can I add middleware to OWIN Pipeline after Startup at runtime. So that Admin can enter the details of new Authentication Server using UI and register new authentication server on demand without disturbing running application.

**Comment by khellang** [comment]
Hey @HarveerNehra! This repository is for the OWIN specification. `IAppBuilder` is for Katana, Microsoft's implementation of the OWIN spec. I suggest you ask over at the [Katana project space](https://katanaproject.codeplex.com/). Thanks! :+1:

**Comment by panesofglass** [comment]
@HarveerNehra, you will need to do something like this: https://github.com/damianh/DynamicKatanaPipeline. The OWIN spec allows for many styles where Katana is one option.

**Comment by HarveerNehra** [comment]
Thanks! I'll try and update accordingly

**Comment by HarveerNehra** [comment]
Actually, I have added 2 External Login.
1. Our Organization ADFS
2. Azure AD
I am using "UseOpenIdConnectAuthentication" method to add external login.

but I have to add other organization's ADFS (our client) external login at run time dynamically.
Any help ?

Thanks in Advance

**Comment by panesofglass** [comment]
@HarveerNehra I tried that a few years ago and eventually gave up and used Auth0. I could never get the OWIN security stuff to work well with multiple orgs / auth patterns.
