### ISSUE TITLE
401 Unauthorized for services on same application server

### ISSUE THREAD

**Issue by ghost** [owin/owin#54]
Hi,

We are hosting multiple webservices with Owin on the same applicationserver. Our services require NTLM authentification. The services are accessed through a DNS-name which points to a load-balancer.
When service A tries to access service B and the load-balancer selects the B instance on the same application server as service A, we are rejected with a 401 unauthorized.
It looks like our issue corresponds nicely to the problem described in this article
https://support.microsoft.com/en-us/help/896861/you-receive-error-401-1-when-you-browse-a-web-site-that-uses-integrate
However the suggested solution here is to update registry keys, which it is not a preferred solution. That is just more configuration when our application servers are replaced or another node is added to the load balancer.
Is there any way this can be solved which does not involve registry keys? Preferably through application code on the client or the host.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetKatana#132

**Comment by serialseb** [comment]
Closing
