### ISSUE TITLE
Create Middleware Specification

### ISSUE THREAD

**Issue by panesofglass** [owin/owin#6]
We have [voted on and accepted](https://groups.google.com/forum/#!topic/net-http-abstractions/cq7DqSSFQ00) `Func<AppFunc, AppFunc>` as the accepted middleware signature, where `AppFunc` is defined as `Func<IDictionary<string, object>, Task>`.

I think this would best be served by a separate, add-on specification rather than as an amendment to the existing OWIN specification. What do others think?

For more information, please refer to the [full discussion on this issue](https://github.com/owin/museum-piece-owin/issues/20).

**Comment by serialseb** [comment]
Specification has been pull-requested, see #41

**Comment by serialseb** [comment]
I suggest closing as duplicate and moving all buildfunc/middleware conversation to the pull request
